"""Regenerate ui/src/logo.js from ui/assets/logo.png.

The explorer ships as ONE self-contained HTML file, so the brand mark cannot
be a separate asset request: Vite is configured with assetsInlineLimit 0 and
tools/build_ui.py only inlines <script>/<link>. Embedding the PNG as a base64
data URI in a JS module is what survives that pipeline.

Two sizes are emitted from the same source: a 96px-tall wordmark (3x the 32px
app-bar render, so it stays crisp on HiDPI) and a 64x64 square favicon that is
letterbox-free in a browser tab. Re-run after changing the source PNG:

    pip install pillow                # dev-only; the engine stays stdlib
    python tools/embed_logo.py
    python tools/build_ui.py          # rebuild the single-file template

The generated ui/src/logo.js is committed, so neither Pillow nor this script
is needed to build or run the explorer.
"""
from __future__ import annotations

import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "ui" / "assets" / "logo.png"
OUT = ROOT / "ui" / "src" / "logo.js"

MARK_HEIGHT = 96   # 3x the 32px app-bar render
ICON_SIDE = 64     # square, for the browser tab


def _data_uri(im: Image.Image) -> str:
    buf = io.BytesIO()
    im.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def main() -> int:
    im = Image.open(SRC).convert("RGBA")
    w, h = im.size

    mark = im.resize((round(w * MARK_HEIGHT / h), MARK_HEIGHT), Image.LANCZOS)

    # Contain the wide mark inside a transparent square so tabs don't squash it.
    icon_w = ICON_SIDE
    icon_h = max(1, round(h * ICON_SIDE / w))
    icon = Image.new("RGBA", (ICON_SIDE, ICON_SIDE), (0, 0, 0, 0))
    icon.alpha_composite(im.resize((icon_w, icon_h), Image.LANCZOS),
                         (0, (ICON_SIDE - icon_h) // 2))

    OUT.write_text(
        "// GENERATED by tools/embed_logo.py from ui/assets/logo.png — do not\n"
        "// hand-edit. Base64 so the single-file explorer needs no asset fetch.\n"
        f'export const LOGO_SRC = "{_data_uri(mark)}";\n'
        f'export const FAVICON_SRC = "{_data_uri(icon)}";\n',
        encoding="utf-8", newline="\n")
    print(f"logo.js -> {OUT} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
